{
 "title": "Eaton UPS Overview",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "ups",
    "query": {
     "query": "label_values(eaton_ups_input_health,ups_id)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eaton_ups_system{ups_id=\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eaton_ups_system{ups_id=\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Watts",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eaton_ups_output_watts{ups_id=~\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output eff.",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eaton_ups_output_efficiency{ups_id=~\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "eaton_ups_battery_state_of_charge{ups_id=\"$ups\"}/100",
     "legendFormat": "Battery"
    },
    {
     "expr": "eaton_ups_output_load_ratio{ups_id=\"$ups\"}",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "Output",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "eaton_ups_output_watts{ups_id=~\"$ups\"}",
     "legendFormat": "Output"
    }
   ]
  },
  {
   "title": "Input health",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eaton_ups_input_health{ups_id=\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bootloader",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eaton_ups_system{ups_id=\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eaton_ups_input_volts{ups_id=~\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Charge",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "eaton_ups_battery_remaining_seconds{ups_id=~\"$ups\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "eaton_ups_temperature{ups_id=~\"$ups\"}",
     "legendFormat": "{{name}} {{position}}"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "eaton_ups_input_volts{ups_id=~\"$ups\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "eaton_ups_input_volts{ups_id=~\"$ups\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Input Wattage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "eaton_ups_output_watts{ups_id=~\"$ups\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "eaton_ups_output_volts{ups_id=~\"$ups\"}",
     "legendFormat": "Voltage"
    }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Charge",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "eaton_ups_battery_state_of_charge{ups_id=~\"$ups\"}",
     "legendFormat": "Charge"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "eaton_ups_battery_volts{ups_id=~\"$ups\"}",
     "legendFormat": "Voltage"
    }
   ]
  }
 ]
}